services:
  agile-studio-server:
   image: krciga22/agile-studio-server:0.1
   container_name: agile-studio-server
   hostname: ${APP_DOMAIN}
   ports:
    - 127.0.0.1:8080:80
    - 127.0.0.1:44360:443
   environment:
     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
     - ASPNETCORE_URLS=https://${APP_DOMAIN}:443;http://${APP_DOMAIN}:80
     - ASPNETCORE_HTTPS_PORTS=44360
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/api-development-agilestudio-dev.pfx
     - ASPNETCORE_Kestrel__Certificates__Default__Password=${APP_CERT_PASSWORD}
     - AUTH0_DOMAIN=${AUTH0_DOMAIN}
     - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
     - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
     - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
     - DB_HOST=${DB_HOST}
     - DB_PORT=3306
     - DB_NAME=${DB_NAME}
     - DB_USER=${DB_USER}
     - DB_PASS=${DB_PASS}
   volumes:
    - ../data/development/certs:/certs:ro
  agile-studio-server-db:
   image: mysql:8.0.42
   container_name: agile-studio-server-db
   ports:
    - 127.0.0.1:33060:3306
   environment:
     - MYSQL_DATABASE=${DB_NAME}
     - MYSQL_USER=${DB_USER}
     - MYSQL_PASSWORD=${DB_PASS}
     - MYSQL_ROOT_PASSWORD=${DB_ROOT_USER_PASSWORD}
   volumes:
    - ../data/development/db:/var/lib/mysql