ServerName development.agilestudio.dev

<VirtualHost *:443>
	ServerName api.development.agilestudio.dev

	CustomLog /app/file-share/logs/access.log common
	ErrorLog /app/file-share/logs/error.log

	SSLEngine on
    SSLCertificateFile /app/file-share/ssl/agile-studio-server.crt
    SSLCertificateKeyFile /app/file-share/ssl/agile-studio-server.key
	SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
	SSLCipherSuite HIGH:!aNULL:!MD5
	SSLHonorCipherOrder on

    RewriteEngine On
    RewriteCond %{HTTP_HOST} !^api\.development\.agilestudio\.dev(:[0-9]+)?$ [NC]
    RewriteRule ^ - [F]

	ProxyPreserveHost On
    ProxyPass        "/" "http://agile-studio-server-app:8081/"
    ProxyPassReverse "/" "http://agile-studio-server-app:8081/"
	ProxyTimeout 60
	RequestHeader set X-Forwarded-Proto "https"
	RequestHeader set X-Forwarded-Port "44360"
	RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
    Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
</VirtualHost>