IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

LogFormat "%v %p %h %l %u %t \"%r\" %>s %b" common
CustomLog ${APACHE_LOG_DIR}/access.log common
ErrorLog ${APACHE_LOG_DIR}/error.log

HostnameLookups Off
DirectoryIndex index.html
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

Include ports.conf

<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>

IncludeOptional sites-enabled/*.conf