# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Agile Studio Server Build

on:
  push:
    branches: [ "v4.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ vars.DB_PORT }}
        TESTCONTAINERS_REUSE_ENABLE: ${{ vars.TESTCONTAINERS_REUSE_ENABLE }}
      run: dotnet test --no-build --verbosity normal
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v2
